apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJkb2NrZXItbWlycm9yLmFydGlmYWN0b3J5LmF0Lml2aS5ydSI6IHsKCQkJImF1dGgiOiAiWVdsMllXNXZkam8yWWtwVlF5RnpiVGxOYVRoQlkwMVNWbkp2UUV0ZmVEY2hjMmdoUmtBPSIKCQl9LAoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJRV3hsZURZeE5qcG5hSEJmTjNWVFFqTlNUbnB3TjBkaFJsbHNPSFJTWlV4WGVqZzNlRlZyWVZOU01XSm5SbTlhIgoJCX0sCgkJImdpdGxhYi1yZWdpc3RyeS5kZXYuaXZpLnJ1IjogewoJCQkiYXV0aCI6ICJZV2wyWVc1dmRqbzJZa3BWUXlGemJUbE5hVGhCWTAxU1ZuSnZRRXRmZURjaGMyZ2hSa0E9IgoJCX0sCgkJImdpdGxhYi5kZXYuaXZpLnJ1IjogewoJCQkiYXV0aCI6ICJZV2wyWVc1dmRqbzJZa3BWUXlGemJUbE5hVGhCWTAxU1ZuSnZRRXRmZURjaGMyZ2hSa0E9IgoJCX0KCX0sCgkiY3VycmVudENvbnRleHQiOiAiY29saW1hIiwKCSJjbGlQbHVnaW5zRXh0cmFEaXJzIjogWwoJCSIvb3B0L2hvbWVicmV3L2xpYi9kb2NrZXIvY2xpLXBsdWdpbnMiCgldCn0=
type: kubernetes.io/dockerconfigjson
